import { Fragment } from "react";
type LegalKind = "privacy" | "cookies";
type LegalLanguage = "en" | "it" | "es" | "fr" | "de" | "pt-BR" | "nl-NL" | "tr" | "pl" | "hu";

const content = {
  en: {
    privacy: {
      title: "Privacy Policy",
      intro: "This Privacy Policy explains how lorem-generator.com handles information when you use the website.",
      sections: [
        ["Text generation", "Lorem Ipsum generation and the text tools available on the site run locally in your browser. Generated text and text entered into these tools are not sent to the site’s application server."],
        ["Local preferences", "The site uses browser local storage to remember interface settings such as your colour theme and your analytics consent preference. This information remains on your device until you change your preferences or clear your browser storage."],
        ["Analytics", <><p>lorem-generator.com uses Ahrefs Web Analytics to understand aggregate website traffic and usage. Ahrefs describes its Web Analytics service as cookie-free and states that it does not collect personal data. On this site, the Ahrefs analytics script is loaded only after you choose to allow analytics.</p><p>You can change your analytics preference through the site’s privacy controls.</p><p>Learn more about <a href="https://ahrefs.com/web-analytics">Ahrefs Web Analytics</a>.</p></>],
        ["Advertising and Google AdSense", <><p>lorem-generator.com uses Google AdSense to display advertising.</p><p>Google and its advertising partners may use cookies, local storage, IP addresses, web beacons or other identifiers in connection with ad delivery, measurement, fraud prevention and, where permitted, ad personalisation.</p><p>For users in the European Economic Area, the United Kingdom and Switzerland, advertising consent is managed through Google Privacy &amp; Messaging, a consent management platform that supports the IAB Europe Transparency &amp; Consent Framework. The message allows users to consent, refuse consent or manage individual options for advertising purposes and participating vendors.</p><p>Users can later review or withdraw their advertising consent through the Privacy and cookie settings provided by Google’s consent system.</p><p>See <a href="https://policies.google.com/technologies/ads">Google’s advertising information</a>.</p></>],
        ["Hosting and security", <><p>lorem-generator.com is delivered through Cloudflare infrastructure. When users access websites delivered through Cloudflare, Cloudflare may process limited technical information such as IP addresses, traffic-routing data, system configuration information and other request-related data necessary to deliver, secure and operate its services.</p><p>See <a href="https://www.cloudflare.com/privacypolicy/">Cloudflare’s privacy documentation</a>.</p></>],
        ["Data retention", "The site does not create user accounts and does not store the text generated with the Lorem Ipsum tools on its application server. Local preferences remain in your browser until you change them or clear browser storage. Information processed by third-party providers is retained according to their respective policies and service configurations."],
        ["Your choices and rights", <><p>Where applicable under data-protection law, you may have rights relating to access, rectification, erasure, restriction, objection, data portability and withdrawal of consent.</p><p>Withdrawing consent does not affect the lawfulness of processing carried out before withdrawal.</p><p>For privacy-related requests concerning lorem-generator.com, contact <a href="mailto:privacy@lorem-generator.com">privacy@lorem-generator.com</a>.</p></>],
        ["Third-party services", <><p>For more information about how third-party providers process information, refer to their respective privacy documentation:</p><ul><li><a href="https://policies.google.com/privacy">Google</a></li><li><a href="https://ahrefs.com/privacy">Ahrefs</a></li><li><a href="https://www.cloudflare.com/privacypolicy/">Cloudflare</a></li></ul></>],
        ["Changes to this policy", "This Privacy Policy may be updated when the site’s services, technologies or data-processing practices change. The version published on this page reflects the current operation of lorem-generator.com."]
      ]
    },
    cookies: {
      title: "Cookie Policy",
      intro: "This Cookie Policy explains how lorem-generator.com uses cookies and browser storage and how you can manage your choices.",
      sections: [
        ["Necessary browser storage", <><p>The site uses browser local storage for essential interface functions, including:</p><ul><li>your colour theme preference;</li><li>your saved analytics consent preference.</li></ul><p>Local storage is not a cookie. These values remain on your device until you change your preferences or clear your browser storage.</p></>],
        ["Analytics", <><p>Ahrefs Web Analytics is used only after analytics consent has been granted.</p><p>Ahrefs describes this service as cookie-free and states that it does not collect personal data. If analytics consent is not granted, the Ahrefs analytics script is not loaded.</p><p>Learn more about <a href="https://ahrefs.com/web-analytics">Ahrefs Web Analytics</a>.</p></>],
        ["Advertising cookies and storage", <><p>Google AdSense may use cookies or other forms of local storage when advertising services are provided. Google states that AdSense uses cookies for functions including ad delivery, frequency control, reporting and, where permitted, personalisation.</p><p>For eligible users in the EEA, the UK and Switzerland, Google Privacy &amp; Messaging manages consent for advertising cookies, local storage and associated processing.</p><p>See <a href="https://policies.google.com/technologies/ads">Google’s advertising information</a>.</p></>],
        ["Managing analytics preferences", "The site’s own privacy controls manage the optional Ahrefs analytics setting. If analytics is disabled, Ahrefs is not loaded on subsequent page loads."],
        ["Managing advertising preferences", "Advertising preferences are managed separately through Google’s consent system. Eligible users can reopen the Google consent interface using the Privacy and cookie settings control and can change or withdraw previous choices."],
        ["Browser controls", "You can also delete cookies and local storage through your browser settings. Doing so may reset saved preferences and may cause consent choices to be requested again."],
        ["Changes to this policy", "This Cookie Policy may be updated when the cookies, browser-storage mechanisms or third-party services used by lorem-generator.com change."]
      ]
    }
  },
  it: {
    privacy: {
      title: "Informativa privacy",
      intro: "Questa informativa descrive come lorem-generator.com tratta le informazioni durante l’utilizzo del sito.",
      sections: [
        ["Generazione del testo", "La generazione di Lorem Ipsum e gli strumenti di testo disponibili sul sito funzionano localmente nel browser. Il testo generato e quello inserito negli strumenti non vengono inviati al server applicativo del sito."],
        ["Preferenze locali", "Il sito utilizza la memoria locale del browser per ricordare alcune impostazioni dell’interfaccia, come il tema colore e la preferenza relativa agli analytics. Queste informazioni rimangono sul dispositivo finché non modifichi le preferenze o cancelli i dati memorizzati dal browser."],
        ["Analytics", <><p>lorem-generator.com utilizza <a href="https://ahrefs.com/it/web-analytics">Ahrefs Web Analytics</a> per comprendere in forma aggregata il traffico e l’utilizzo del sito. Ahrefs descrive il proprio servizio Web Analytics come privo di cookie e dichiara di non raccogliere dati personali. Su questo sito lo script di Ahrefs viene caricato solo dopo che l’utente ha scelto di consentire gli analytics.</p><p>La preferenza relativa agli analytics può essere modificata tramite i controlli privacy del sito.</p></>],
        ["Pubblicità e Google AdSense", <><p>lorem-generator.com utilizza Google AdSense per mostrare contenuti pubblicitari.</p><p>Google e i suoi partner pubblicitari possono utilizzare cookie, archiviazione locale, indirizzi IP, web beacon o altri identificatori in relazione alla pubblicazione e misurazione degli annunci, alla prevenzione delle frodi e, quando consentito, alla personalizzazione della pubblicità.</p><p>Per gli utenti dello Spazio economico europeo, del Regno Unito e della Svizzera, le preferenze relative alla pubblicità sono gestite tramite Google Privacy e messaggi, una piattaforma di gestione del consenso compatibile con il Transparency &amp; Consent Framework di IAB Europe. Il messaggio permette di acconsentire, negare il consenso o gestire singolarmente le opzioni relative alle finalità pubblicitarie e ai fornitori coinvolti.</p><p>Le preferenze pubblicitarie possono essere successivamente modificate o revocate tramite le impostazioni relative alla privacy e ai cookie messe a disposizione dal sistema di consenso Google.</p><p>Consulta le <a href="https://policies.google.com/technologies/ads?hl=it">informazioni di Google sulla pubblicità</a>.</p></>],
        ["Hosting e sicurezza", <><p>lorem-generator.com viene distribuito attraverso l’infrastruttura Cloudflare. Durante l’accesso al sito, Cloudflare può trattare informazioni tecniche limitate, tra cui indirizzi IP, dati di instradamento del traffico, informazioni sulla configurazione del sistema e altri dati relativi alle richieste, necessari per distribuire, proteggere e gestire il servizio.</p><p>Consulta la <a href="https://www.cloudflare.com/it-it/privacypolicy/">documentazione sulla privacy di Cloudflare</a>.</p></>],
        ["Conservazione dei dati", "Il sito non crea account utente e non memorizza sul proprio server applicativo il testo generato tramite gli strumenti Lorem Ipsum. Le preferenze locali restano memorizzate nel browser finché non vengono modificate o cancellate. Le informazioni eventualmente trattate dai fornitori terzi vengono conservate secondo le rispettive informative e configurazioni dei servizi."],
        ["Scelte e diritti dell’utente", <><p>Quando previsto dalla normativa applicabile, l’utente può esercitare i diritti relativi ad accesso, rettifica, cancellazione, limitazione del trattamento, opposizione, portabilità dei dati e revoca del consenso.</p><p>La revoca del consenso non pregiudica la liceità dei trattamenti effettuati prima della revoca.</p><p>Per richieste relative alla privacy di lorem-generator.com è possibile contattare <a href="mailto:privacy@lorem-generator.com">privacy@lorem-generator.com</a>.</p></>],
        ["Servizi di terze parti", <><p>Per maggiori informazioni sul trattamento effettuato dai fornitori terzi è possibile consultare le rispettive informative:</p><ul><li><a href="https://policies.google.com/privacy?hl=it">Google</a></li><li><a href="https://ahrefs.com/privacy">Ahrefs</a></li><li><a href="https://www.cloudflare.com/it-it/privacypolicy/">Cloudflare</a></li></ul></>],
        ["Modifiche all’informativa", "Questa informativa può essere aggiornata quando cambiano i servizi, le tecnologie o le modalità di trattamento dei dati utilizzate dal sito. La versione pubblicata in questa pagina descrive il funzionamento attuale di lorem-generator.com."]
      ]
    },
    cookies: {
      title: "Informativa sui cookie",
      intro: "Questa informativa descrive l’utilizzo di cookie e memoria del browser da parte di lorem-generator.com e spiega come gestire le proprie preferenze.",
      sections: [
        ["Memoria locale necessaria", <><p>Il sito utilizza la memoria locale del browser per alcune funzioni dell’interfaccia, tra cui:</p><ul><li>la preferenza relativa al tema colore;</li><li>la preferenza salvata relativa agli analytics.</li></ul><p>La memoria locale non è un cookie. Questi valori rimangono sul dispositivo finché non vengono modificati oppure cancellati dalle impostazioni del browser.</p></>],
        ["Analytics", <><p><a href="https://ahrefs.com/it/web-analytics">Ahrefs Web Analytics</a> viene utilizzato soltanto dopo che l’utente ha espresso il consenso agli analytics.</p><p>Ahrefs descrive questo servizio come privo di cookie e dichiara di non raccogliere dati personali. Se il consenso agli analytics non viene fornito, lo script Ahrefs non viene caricato.</p></>],
        ["Cookie e archiviazione per la pubblicità", <><p>Google AdSense può utilizzare cookie o altre forme di archiviazione locale durante l’erogazione dei servizi pubblicitari. Secondo Google, i cookie di AdSense possono essere utilizzati, tra le altre cose, per pubblicare annunci, limitarne la frequenza, misurarne le prestazioni e, quando consentito, personalizzarli.</p><p>Per gli utenti interessati nello SEE, nel Regno Unito e in Svizzera, Google Privacy e messaggi gestisce il consenso relativo ai cookie pubblicitari, all’archiviazione locale e ai trattamenti collegati.</p><p>Consulta le <a href="https://policies.google.com/technologies/ads?hl=it">informazioni di Google sulla pubblicità</a>.</p></>],
        ["Gestione delle preferenze analytics", "I controlli privacy propri di lorem-generator.com gestiscono esclusivamente la preferenza opzionale relativa ad Ahrefs Analytics. Quando gli analytics vengono disabilitati, Ahrefs non viene caricato ai successivi caricamenti della pagina."],
        ["Gestione delle preferenze pubblicitarie", "Le preferenze pubblicitarie sono gestite separatamente tramite il sistema di consenso Google. Gli utenti interessati possono riaprire l’interfaccia Google tramite il comando Impostazioni relative alla privacy e ai cookie e modificare o revocare le scelte effettuate in precedenza."],
        ["Impostazioni del browser", "Cookie e memoria locale possono essere eliminati anche attraverso le impostazioni del browser. Questa operazione può reimpostare le preferenze salvate e comportare una nuova richiesta di consenso."],
        ["Modifiche all’informativa", "Questa informativa può essere aggiornata quando cambiano i cookie, i meccanismi di archiviazione del browser o i servizi di terze parti utilizzati da lorem-generator.com."]
      ]
    }
  }
} as const;

const spanishPrivacy = {
  title: "Política de privacidad",
  intro: "Esta Política de privacidad explica cómo lorem-generator.com trata la información cuando utilizas el sitio web.",
  sections: [
    ["Generación de texto", "La generación de Lorem Ipsum y las herramientas de texto disponibles en el sitio funcionan localmente en tu navegador. El texto generado y el texto introducido en estas herramientas no se envían al servidor de aplicaciones del sitio."],
    ["Preferencias locales", "El sitio utiliza el almacenamiento local del navegador para recordar determinados ajustes de la interfaz, como el tema de color y tu preferencia de consentimiento para las estadísticas de uso. Esta información permanece en tu dispositivo hasta que cambies tus preferencias o elimines los datos almacenados por el navegador."],
    ["Estadísticas de uso", <><p>lorem-generator.com utiliza Ahrefs Web Analytics para conocer de forma agregada el tráfico y el uso del sitio.</p><p>Ahrefs describe Web Analytics como un servicio sin cookies e indica que no recopila datos personales. En este sitio, el script de Ahrefs solo se carga después de que el usuario haya aceptado las estadísticas de uso.</p><p>Puedes modificar esta preferencia mediante los controles de privacidad del sitio.</p><p>Más información sobre <a href="https://ahrefs.com/web-analytics">Ahrefs Web Analytics</a>.</p></>],
    ["Publicidad y Google AdSense", <><p>lorem-generator.com utiliza Google AdSense para mostrar publicidad.</p><p>Google y sus partners publicitarios pueden utilizar cookies, almacenamiento local, direcciones IP, balizas web u otros identificadores para la publicación y medición de anuncios, la prevención del fraude y, cuando esté permitido, la personalización de la publicidad.</p><p>Para los usuarios del Espacio Económico Europeo (EEE), Reino Unido y Suiza, las preferencias relacionadas con la publicidad se gestionan mediante Google Privacidad y mensajes, una plataforma de gestión del consentimiento compatible con el Transparency &amp; Consent Framework de IAB Europe.</p><p>El mensaje permite consentir, no consentir o gestionar de forma individual las opciones relacionadas con las finalidades publicitarias y los proveedores participantes.</p><p>Posteriormente, los usuarios pueden revisar, modificar o retirar su consentimiento mediante los ajustes de privacidad y cookies proporcionados por el sistema de consentimiento de Google.</p><p>Consulta la <a href="https://policies.google.com/technologies/ads?hl=es">información de Google sobre publicidad</a>.</p></>],
    ["Alojamiento y seguridad", <><p>lorem-generator.com se distribuye mediante la infraestructura de Cloudflare.</p><p>Al acceder al sitio, Cloudflare puede tratar información técnica limitada, como direcciones IP, datos de enrutamiento del tráfico, información sobre la configuración del sistema y otros datos relacionados con las solicitudes que sean necesarios para prestar, proteger y operar sus servicios.</p><p>Consulta la <a href="https://www.cloudflare.com/es-es/privacypolicy/">documentación de privacidad de Cloudflare</a>.</p></>],
    ["Conservación de los datos", "El sitio no crea cuentas de usuario ni almacena en su servidor de aplicaciones el texto generado con las herramientas de Lorem Ipsum. Las preferencias locales permanecen en el navegador hasta que se modifiquen o se eliminen los datos del navegador. La información que puedan tratar proveedores externos se conserva de acuerdo con sus respectivas políticas y configuraciones de servicio."],
    ["Tus opciones y derechos", <><p>Cuando lo prevea la normativa de protección de datos aplicable, puedes tener derechos de acceso, rectificación, supresión, limitación del tratamiento, oposición, portabilidad de los datos y retirada del consentimiento.</p><p>La retirada del consentimiento no afecta a la licitud de los tratamientos realizados antes de dicha retirada.</p><p>Para solicitudes relacionadas con la privacidad de lorem-generator.com, puedes escribir a <a href="mailto:privacy@lorem-generator.com">privacy@lorem-generator.com</a>.</p></>],
    ["Servicios de terceros", <><p>Para obtener más información sobre cómo tratan la información los proveedores externos, consulta sus respectivas políticas de privacidad:</p><ul><li><a href="https://policies.google.com/privacy?hl=es">Google</a></li><li><a href="https://ahrefs.com/privacy">Ahrefs</a></li><li><a href="https://www.cloudflare.com/es-es/privacypolicy/">Cloudflare</a></li></ul></>],
    ["Cambios en esta política", "Esta Política de privacidad puede actualizarse cuando cambien los servicios, las tecnologías o las prácticas de tratamiento de datos utilizadas por el sitio. La versión publicada en esta página describe el funcionamiento actual de lorem-generator.com."]
  ]
} as const;

const spanishCookies = {
  title: "Política de cookies",
  intro: "Esta política explica cómo lorem-generator.com utiliza las cookies y el almacenamiento del navegador, así como la forma de gestionar tus preferencias.",
  sections: [
    ["Almacenamiento local necesario", <><p>El sitio utiliza el almacenamiento local del navegador para determinadas funciones de la interfaz, entre ellas:</p><ul><li>tu preferencia de tema de color;</li><li>tu preferencia guardada sobre las estadísticas de uso.</li></ul><p>El almacenamiento local no es una cookie. Estos valores permanecen en tu dispositivo hasta que cambies tus preferencias o elimines los datos almacenados por el navegador.</p></>],
    ["Estadísticas de uso", <><p>Ahrefs Web Analytics se utiliza únicamente después de que el usuario haya dado su consentimiento para las estadísticas de uso.</p><p>Ahrefs describe este servicio como libre de cookies e indica que no recopila datos personales.</p><p>Si no se da el consentimiento para las estadísticas de uso, el script de Ahrefs no se carga.</p><p>Más información sobre <a href="https://ahrefs.com/web-analytics">Ahrefs Web Analytics</a>.</p></>],
    ["Cookies y almacenamiento para publicidad", <><p>Google AdSense puede utilizar cookies u otras formas de almacenamiento local al prestar servicios publicitarios.</p><p>Según Google, las cookies de AdSense pueden utilizarse, entre otras finalidades, para publicar anuncios, limitar su frecuencia, medir su rendimiento y, cuando esté permitido, personalizarlos.</p><p>Para los usuarios correspondientes del EEE, Reino Unido y Suiza, Google Privacidad y mensajes gestiona el consentimiento relativo a las cookies publicitarias, el almacenamiento local y los tratamientos asociados.</p><p>Consulta la <a href="https://policies.google.com/technologies/ads?hl=es">información de Google sobre publicidad</a>.</p></>],
    ["Gestión de las preferencias de estadísticas de uso", "Los controles de privacidad propios de lorem-generator.com gestionan exclusivamente la preferencia opcional relativa a Ahrefs Web Analytics. Cuando las estadísticas de uso se desactivan, Ahrefs no se carga en las siguientes cargas de página."],
    ["Gestión de las preferencias publicitarias", "Las preferencias publicitarias se gestionan por separado mediante el sistema de consentimiento de Google. Los usuarios correspondientes pueden volver a abrir la interfaz de Google mediante el control de ajustes de privacidad y cookies y modificar o retirar las decisiones tomadas anteriormente."],
    ["Configuración del navegador", "También puedes eliminar las cookies y el almacenamiento local desde la configuración de tu navegador. Esta operación puede restablecer las preferencias guardadas y hacer que se solicite de nuevo el consentimiento."],
    ["Cambios en esta política", "Esta Política de cookies puede actualizarse cuando cambien las cookies, los mecanismos de almacenamiento del navegador o los servicios de terceros utilizados por lorem-generator.com."]
  ]
} as const;

const frenchPrivacy = {
  title: "Politique de confidentialité",
  intro: "La présente politique de confidentialité explique comment lorem-generator.com traite les informations lorsque vous utilisez le site.",
  sections: [
    ["Génération de texte", "La génération de Lorem Ipsum et les outils de texte disponibles sur le site fonctionnent localement dans votre navigateur. Le texte généré et celui saisi dans ces outils ne sont pas envoyés au serveur applicatif du site."],
    ["Préférences locales", "Le site utilise le stockage local du navigateur pour mémoriser certains réglages de l’interface, comme le thème de couleur et votre choix relatif aux statistiques d’audience. Ces informations restent sur votre appareil jusqu’à ce que vous modifiiez vos préférences ou supprimiez les données stockées par votre navigateur."],
    ["Statistiques d’audience", <><p>lorem-generator.com utilise Ahrefs Web Analytics afin de comprendre, de manière agrégée, le trafic et l’utilisation du site.</p><p>Ahrefs présente son service Web Analytics comme fonctionnant sans cookies et indique qu’il ne collecte pas de données personnelles. Sur ce site, le script Ahrefs n’est chargé qu’après votre accord pour les statistiques d’audience.</p><p>Vous pouvez modifier ce choix à tout moment à l’aide des paramètres de confidentialité du site.</p><p>En savoir plus sur <a href="https://ahrefs.com/web-analytics">Ahrefs Web Analytics</a>.</p></>],
    ["Publicité et Google AdSense", <><p>lorem-generator.com utilise Google AdSense pour afficher des annonces publicitaires.</p><p>Google et ses partenaires publicitaires peuvent utiliser des cookies, le stockage local, des adresses IP, des balises Web ou d’autres identifiants pour la diffusion et la mesure des annonces, la prévention de la fraude et, lorsque cela est autorisé, la personnalisation de la publicité.</p><p>Pour les utilisateurs situés dans l’Espace économique européen (EEE), au Royaume-Uni et en Suisse, les choix relatifs à la publicité sont gérés via Google Confidentialité et messages, une plate-forme de gestion du consentement compatible avec le Transparency &amp; Consent Framework d’IAB Europe.</p><p>Le message permet d’accepter, de refuser ou de gérer individuellement les options liées aux finalités publicitaires et aux fournisseurs concernés.</p><p>Les utilisateurs peuvent ensuite consulter, modifier ou retirer leur consentement à l’aide des paramètres de confidentialité et de cookies fournis par le système de consentement de Google.</p><p>Consulter les <a href="https://policies.google.com/technologies/ads?hl=fr">informations de Google sur la publicité</a>.</p></>],
    ["Hébergement et sécurité", <><p>lorem-generator.com est distribué via l’infrastructure Cloudflare. Lors de l’accès au site, Cloudflare peut traiter certaines informations techniques limitées, notamment les adresses IP, les données liées à l’acheminement du trafic, les informations de configuration du système et d’autres données relatives aux requêtes nécessaires à la fourniture, à la sécurisation et au fonctionnement de ses services.</p><p>Consulter la <a href="https://www.cloudflare.com/fr-fr/privacypolicy/">documentation de Cloudflare relative à la confidentialité</a>.</p></>],
    ["Conservation des données", "Le site ne crée pas de comptes utilisateur et ne stocke pas sur son serveur applicatif le texte généré avec les outils Lorem Ipsum. Les préférences locales restent enregistrées dans votre navigateur jusqu’à ce que vous les modifiiez ou supprimiez les données du navigateur. Les informations éventuellement traitées par des prestataires tiers sont conservées conformément à leurs propres politiques et à la configuration de leurs services."],
    ["Vos choix et vos droits", <><p>Lorsque la législation applicable le prévoit, vous pouvez disposer de droits concernant l’accès, la rectification, l’effacement, la limitation du traitement, l’opposition, la portabilité des données et le retrait du consentement.</p><p>Le retrait du consentement ne remet pas en cause la licéité des traitements effectués avant ce retrait.</p><p>Pour toute demande relative à la confidentialité concernant lorem-generator.com, contactez <a href="mailto:privacy@lorem-generator.com">privacy@lorem-generator.com</a>.</p></>],
    ["Services tiers", <><p>Pour en savoir plus sur le traitement des informations par les prestataires tiers, consultez leurs politiques de confidentialité respectives :</p><ul><li><a href="https://policies.google.com/privacy?hl=fr">Google</a></li><li><a href="https://ahrefs.com/privacy">Ahrefs</a></li><li><a href="https://www.cloudflare.com/fr-fr/privacypolicy/">Cloudflare</a></li></ul></>],
    ["Modifications de la présente politique", "La présente politique de confidentialité peut être mise à jour lorsque les services, les technologies ou les pratiques de traitement des données utilisés par le site évoluent. La version publiée sur cette page décrit le fonctionnement actuel de lorem-generator.com."]
  ]
} as const;

const frenchCookies = {
  title: "Politique relative aux cookies",
  intro: "La présente politique explique comment lorem-generator.com utilise les cookies et le stockage du navigateur, ainsi que la manière dont vous pouvez gérer vos choix.",
  sections: [
    ["Stockage local nécessaire", <><p>Le site utilise le stockage local du navigateur pour certaines fonctions de l’interface, notamment :</p><ul><li>votre préférence de thème de couleur ;</li><li>votre choix enregistré concernant les statistiques d’audience.</li></ul><p>Le stockage local n’est pas un cookie. Ces valeurs restent sur votre appareil jusqu’à ce que vous modifiiez vos préférences ou supprimiez les données stockées par votre navigateur.</p></>],
    ["Statistiques d’audience", <><p>Ahrefs Web Analytics est utilisé uniquement après que vous avez donné votre consentement aux statistiques d’audience.</p><p>Ahrefs présente ce service comme fonctionnant sans cookies et indique qu’il ne collecte pas de données personnelles. Si vous ne donnez pas votre consentement aux statistiques d’audience, le script Ahrefs n’est pas chargé.</p><p>En savoir plus sur <a href="https://ahrefs.com/web-analytics">Ahrefs Web Analytics</a>.</p></>],
    ["Cookies et stockage liés à la publicité", <><p>Google AdSense peut utiliser des cookies ou d’autres formes de stockage local dans le cadre de ses services publicitaires.</p><p>Selon Google, les cookies AdSense peuvent notamment être utilisés pour diffuser des annonces, limiter leur fréquence, mesurer leurs performances et, lorsque cela est autorisé, les personnaliser.</p><p>Pour les utilisateurs concernés dans l’EEE, au Royaume-Uni et en Suisse, Google Confidentialité et messages gère le consentement relatif aux cookies publicitaires, au stockage local et aux traitements associés.</p><p>Consulter les <a href="https://policies.google.com/technologies/ads?hl=fr">informations de Google sur la publicité</a>.</p></>],
    ["Gestion des préférences de statistiques d’audience", "Les paramètres de confidentialité propres à lorem-generator.com gèrent uniquement le choix facultatif relatif à Ahrefs Web Analytics. Lorsque les statistiques d’audience sont désactivées, Ahrefs n’est pas chargé lors des chargements de page suivants."],
    ["Gestion des préférences publicitaires", "Les préférences publicitaires sont gérées séparément via le système de consentement de Google. Les utilisateurs concernés peuvent rouvrir l’interface Google au moyen du contrôle relatif aux paramètres de confidentialité et de cookies, puis modifier ou retirer leurs choix précédents."],
    ["Paramètres du navigateur", "Vous pouvez également supprimer les cookies et le stockage local depuis les paramètres de votre navigateur. Cette opération peut réinitialiser les préférences enregistrées et entraîner une nouvelle demande de consentement."],
    ["Modifications de la présente politique", "La présente politique peut être mise à jour lorsque les cookies, les mécanismes de stockage du navigateur ou les services tiers utilisés par lorem-generator.com évoluent."]
  ]
} as const;

const germanPrivacy = {
  title: "Datenschutzerklärung",
  intro: "Diese Datenschutzerklärung erläutert, wie lorem-generator.com Informationen bei der Nutzung der Website verarbeitet.",
  sections: [
    ["Textgenerierung", "Die Lorem-Ipsum-Generierung und die auf der Website verfügbaren Textwerkzeuge werden lokal in Ihrem Browser ausgeführt. Generierter Text und Text, den Sie in diese Werkzeuge eingeben, werden nicht an den Anwendungsserver der Website übertragen."],
    ["Lokale Einstellungen", "Die Website verwendet den lokalen Speicher Ihres Browsers, um bestimmte Einstellungen der Benutzeroberfläche zu speichern, beispielsweise das Farbschema und Ihre Einwilligungseinstellung für Webanalyse. Diese Informationen verbleiben auf Ihrem Gerät, bis Sie Ihre Einstellungen ändern oder die im Browser gespeicherten Daten löschen."],
    ["Webanalyse", <><p>lorem-generator.com verwendet Ahrefs Web Analytics, um aggregierte Informationen über den Website-Traffic und die Nutzung der Website zu erhalten.</p><p>Ahrefs beschreibt Web Analytics als cookiefreien Dienst und gibt an, dabei keine personenbezogenen Daten zu erfassen. Auf dieser Website wird das Ahrefs-Analytics-Skript erst geladen, nachdem Sie der Webanalyse zugestimmt haben.</p><p>Sie können Ihre Einstellung zur Webanalyse über die Datenschutzeinstellungen der Website ändern.</p><p>Weitere Informationen zu <a href="https://ahrefs.com/web-analytics">Ahrefs Web Analytics</a>.</p></>],
    ["Werbung und Google AdSense", <><p>lorem-generator.com verwendet Google AdSense zur Anzeige von Werbung.</p><p>Google und seine Werbepartner können Cookies, lokale Speicherverfahren, IP-Adressen, Web-Beacons oder andere Kennungen im Zusammenhang mit der Auslieferung und Messung von Anzeigen, der Betrugsprävention und – sofern zulässig – der Personalisierung von Werbung verwenden.</p><p>Für Nutzerinnen und Nutzer im Europäischen Wirtschaftsraum (EWR), im Vereinigten Königreich und in der Schweiz werden die Einwilligungseinstellungen für Werbung über Google „Datenschutz und Mitteilungen“ verwaltet, eine Plattform zur Einwilligungsverwaltung, die das Transparency &amp; Consent Framework von IAB Europe unterstützt.</p><p>Die Mitteilung ermöglicht es Nutzern, einzuwilligen, die Einwilligung abzulehnen oder einzelne Optionen für Werbezwecke und beteiligte Anbieter zu verwalten.</p><p>Werbeeinstellungen können später über die von Googles Einwilligungssystem bereitgestellten Datenschutz- und Cookie-Einstellungen überprüft, geändert oder widerrufen werden.</p><p>Weitere Informationen zur <a href="https://policies.google.com/technologies/ads?hl=de">Werbung von Google</a>.</p></>],
    ["Hosting und Sicherheit", <><p>lorem-generator.com wird über die Infrastruktur von Cloudflare bereitgestellt. Beim Zugriff auf die Website kann Cloudflare begrenzte technische Informationen verarbeiten, darunter IP-Adressen, Daten zur Weiterleitung des Datenverkehrs, Informationen zur Systemkonfiguration und weitere anfragebezogene Daten, die für die Bereitstellung, Absicherung und den Betrieb seiner Dienste erforderlich sind.</p><p>Weitere Informationen in der <a href="https://www.cloudflare.com/de-de/privacypolicy/">Datenschutzerklärung von Cloudflare</a>.</p></>],
    ["Speicherdauer", "Die Website erstellt keine Benutzerkonten und speichert den mit den Lorem-Ipsum-Werkzeugen erzeugten Text nicht auf ihrem Anwendungsserver. Lokale Einstellungen verbleiben im Browser, bis Sie diese ändern oder die Browserdaten löschen. Informationen, die von Drittanbietern verarbeitet werden, werden gemäß deren jeweiligen Datenschutzbestimmungen und Dienstkonfigurationen gespeichert."],
    ["Ihre Wahlmöglichkeiten und Rechte", <><p>Soweit nach dem anwendbaren Datenschutzrecht vorgesehen, können Ihnen Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung, Widerspruch, Datenübertragbarkeit und Widerruf einer Einwilligung zustehen.</p><p>Der Widerruf einer Einwilligung berührt nicht die Rechtmäßigkeit der Verarbeitung, die vor dem Widerruf auf Grundlage der Einwilligung erfolgt ist.</p><p>Für datenschutzbezogene Anfragen zu lorem-generator.com kontaktieren Sie <a href="mailto:privacy@lorem-generator.com">privacy@lorem-generator.com</a>.</p></>],
    ["Dienste von Drittanbietern", <><p>Weitere Informationen darüber, wie Drittanbieter Informationen verarbeiten, finden Sie in deren jeweiligen Datenschutzerklärungen:</p><ul><li><a href="https://policies.google.com/privacy?hl=de">Google</a></li><li><a href="https://ahrefs.com/privacy">Ahrefs</a></li><li><a href="https://www.cloudflare.com/de-de/privacypolicy/">Cloudflare</a></li></ul></>],
    ["Änderungen dieser Datenschutzerklärung", "Diese Datenschutzerklärung kann aktualisiert werden, wenn sich die von der Website eingesetzten Dienste, Technologien oder Datenverarbeitungspraktiken ändern. Die auf dieser Seite veröffentlichte Version beschreibt den aktuellen Betrieb von lorem-generator.com."]
  ]
} as const;

const germanCookies = {
  title: "Cookie-Richtlinie",
  intro: "Diese Richtlinie erläutert, wie lorem-generator.com Cookies und Browserspeicher verwendet und wie Sie Ihre Einstellungen verwalten können.",
  sections: [
    ["Erforderlicher lokaler Speicher", <><p>Die Website verwendet den lokalen Speicher Ihres Browsers für bestimmte Funktionen der Benutzeroberfläche, darunter:</p><ul><li>Ihre Einstellung für das Farbschema;</li><li>Ihre gespeicherte Einwilligungseinstellung für Webanalyse.</li></ul><p>Lokaler Speicher ist kein Cookie. Diese Werte verbleiben auf Ihrem Gerät, bis Sie Ihre Einstellungen ändern oder die im Browser gespeicherten Daten löschen.</p></>],
    ["Webanalyse", <><p>Ahrefs Web Analytics wird nur verwendet, wenn Sie der Webanalyse zuvor zugestimmt haben.</p><p>Ahrefs beschreibt diesen Dienst als cookiefrei und gibt an, dabei keine personenbezogenen Daten zu erfassen. Wenn Sie der Webanalyse nicht zustimmen, wird das Ahrefs-Analytics-Skript nicht geladen.</p><p>Weitere Informationen zu <a href="https://ahrefs.com/web-analytics">Ahrefs Web Analytics</a>.</p></>],
    ["Cookies und lokale Speicherung für Werbung", <><p>Google AdSense kann bei der Bereitstellung von Werbediensten Cookies oder andere lokale Speicherverfahren verwenden.</p><p>Nach Angaben von Google können AdSense-Cookies unter anderem für die Auslieferung von Anzeigen, die Begrenzung der Anzeigenhäufigkeit, die Erfolgsmessung und – sofern zulässig – die Personalisierung von Werbung verwendet werden.</p><p>Für betroffene Nutzerinnen und Nutzer im EWR, im Vereinigten Königreich und in der Schweiz verwaltet Google „Datenschutz und Mitteilungen“ die Einwilligung für Werbe-Cookies, lokale Speicherverfahren und die damit verbundenen Verarbeitungsvorgänge.</p><p>Weitere Informationen zur <a href="https://policies.google.com/technologies/ads?hl=de">Werbung von Google</a>.</p></>],
    ["Verwaltung der Webanalyse-Einstellungen", "Die eigenen Datenschutzeinstellungen von lorem-generator.com verwalten ausschließlich die optionale Einwilligung für Ahrefs Web Analytics. Wenn die Webanalyse deaktiviert wird, wird Ahrefs bei nachfolgenden Seitenaufrufen nicht geladen."],
    ["Verwaltung der Werbeeinstellungen", "Werbeeinstellungen werden separat über das Einwilligungssystem von Google verwaltet. Betroffene Nutzerinnen und Nutzer können die Google-Oberfläche über die Datenschutz- und Cookie-Einstellungen erneut öffnen und zuvor getroffene Entscheidungen ändern oder widerrufen."],
    ["Browsereinstellungen", "Sie können Cookies und lokalen Speicher auch über die Einstellungen Ihres Browsers löschen. Dadurch können gespeicherte Einstellungen zurückgesetzt werden und eine erneute Abfrage der Einwilligung erforderlich werden."],
    ["Änderungen dieser Richtlinie", "Diese Richtlinie kann aktualisiert werden, wenn sich die von lorem-generator.com verwendeten Cookies, Mechanismen zur Browserspeicherung oder Dienste von Drittanbietern ändern."]
  ]
} as const;

const brazilianPortuguesePrivacy = {
  title: "Política de Privacidade",
  intro: "Esta Política de Privacidade explica como o lorem-generator.com trata informações quando você utiliza o site.",
  sections: [
    ["Geração de texto", <><p>A geração de Lorem Ipsum e as ferramentas de texto disponíveis no site funcionam localmente no seu navegador.</p><p>O texto gerado e o texto inserido nessas ferramentas não são enviados ao servidor de aplicação do site.</p></>],
    ["Preferências locais", <><p>O site utiliza o armazenamento local do navegador para lembrar algumas configurações da interface, como o tema de cores e sua preferência de consentimento para análise de uso.</p><p>Essas informações permanecem no seu dispositivo até que você altere suas preferências ou exclua os dados armazenados pelo navegador.</p></>],
    ["Análise de uso", <><p>O lorem-generator.com utiliza o Ahrefs Web Analytics para compreender, de forma agregada, o tráfego e a utilização do site.</p><p>A Ahrefs descreve o Web Analytics como um serviço sem cookies e informa que não coleta dados pessoais. Neste site, o script da Ahrefs só é carregado depois que o usuário autoriza a análise de uso.</p><p>Você pode alterar essa preferência pelos controles de privacidade do site.</p><p>Saiba mais sobre o <a href="https://ahrefs.com/web-analytics">Ahrefs Web Analytics</a>.</p></>],
    ["Publicidade e Google AdSense", <><p>O lorem-generator.com utiliza o Google AdSense para exibir anúncios.</p><p>O Google e seus parceiros de publicidade podem utilizar cookies, armazenamento local, endereços IP, web beacons ou outros identificadores relacionados à exibição e medição de anúncios, prevenção de fraudes e, quando permitido, personalização da publicidade.</p><p>Para usuários no Espaço Econômico Europeu (EEE), no Reino Unido e na Suíça, as preferências relacionadas à publicidade são gerenciadas por meio do Google Privacidade e mensagens, uma plataforma de gerenciamento de consentimento compatível com o Transparency &amp; Consent Framework do IAB Europe.</p><p>A mensagem permite consentir, não consentir ou gerenciar individualmente as opções relacionadas às finalidades publicitárias e aos fornecedores participantes.</p><p>Posteriormente, os usuários podem revisar, alterar ou revogar o consentimento por meio das configurações de privacidade e cookies fornecidas pelo sistema de consentimento do Google.</p><p>Consulte as <a href="https://policies.google.com/technologies/ads?hl=pt-BR">informações do Google sobre publicidade</a>.</p></>],
    ["Hospedagem e segurança", <><p>O lorem-generator.com é disponibilizado por meio da infraestrutura da Cloudflare.</p><p>Ao acessar o site, a Cloudflare pode tratar informações técnicas limitadas, como endereços IP, dados de roteamento de tráfego, informações de configuração do sistema e outros dados relacionados às solicitações necessários para fornecer, proteger e operar seus serviços.</p><p>Consulte a <a href="https://www.cloudflare.com/pt-br/privacypolicy/">documentação de privacidade da Cloudflare</a>.</p></>],
    ["Retenção de dados", <><p>O site não cria contas de usuário e não armazena, em seu servidor de aplicação, o texto gerado pelas ferramentas de Lorem Ipsum.</p><p>As preferências locais permanecem no navegador até que sejam alteradas ou que os dados armazenados pelo navegador sejam excluídos.</p><p>As informações eventualmente tratadas por fornecedores terceiros são mantidas de acordo com suas respectivas políticas e configurações de serviço.</p></>],
    ["Suas escolhas e seus direitos", <><p>Quando previsto pela legislação de proteção de dados aplicável, você pode ter direitos relacionados ao acesso, à correção, à exclusão, à limitação ou oposição ao tratamento, à portabilidade dos dados e à revogação do consentimento.</p><p>A revogação do consentimento não afeta a legalidade dos tratamentos realizados anteriormente com base no consentimento.</p><p>Para solicitações relacionadas à privacidade do lorem-generator.com, entre em contato pelo endereço <a href="mailto:privacy@lorem-generator.com">privacy@lorem-generator.com</a>.</p></>],
    ["Serviços de terceiros", <><p>Para saber mais sobre como fornecedores terceiros tratam informações, consulte suas respectivas políticas de privacidade:</p><ul><li><a href="https://policies.google.com/privacy?hl=pt-BR">Google</a></li><li><a href="https://ahrefs.com/privacy">Ahrefs</a></li><li><a href="https://www.cloudflare.com/pt-br/privacypolicy/">Cloudflare</a></li></ul></>],
    ["Alterações nesta política", <><p>Esta Política de Privacidade pode ser atualizada quando houver mudanças nos serviços, nas tecnologias ou nas práticas de tratamento de dados utilizadas pelo site.</p><p>A versão publicada nesta página descreve o funcionamento atual do lorem-generator.com.</p></>]
  ]
} as const;

const brazilianPortugueseCookies = {
  title: "Política de Cookies",
  intro: "Esta política explica como o lorem-generator.com utiliza cookies e o armazenamento do navegador e como você pode gerenciar suas preferências.",
  sections: [
    ["Armazenamento local necessário", <><p>O site utiliza o armazenamento local do navegador para determinadas funções da interface, incluindo:</p><ul><li>sua preferência de tema de cores;</li><li>sua preferência salva sobre análise de uso.</li></ul><p>O armazenamento local não é um cookie. Esses valores permanecem no seu dispositivo até que você altere suas preferências ou exclua os dados armazenados pelo navegador.</p></>],
    ["Análise de uso", <><p>O Ahrefs Web Analytics é utilizado somente depois que o usuário concede consentimento para a análise de uso.</p><p>A Ahrefs descreve esse serviço como livre de cookies e informa que não coleta dados pessoais.</p><p>Se o consentimento para análise de uso não for concedido, o script da Ahrefs não é carregado.</p><p>Saiba mais sobre o <a href="https://ahrefs.com/web-analytics">Ahrefs Web Analytics</a>.</p></>],
    ["Cookies e armazenamento para publicidade", <><p>O Google AdSense pode utilizar cookies ou outras formas de armazenamento local durante a prestação de serviços de publicidade.</p><p>Segundo o Google, os cookies do AdSense podem ser utilizados, entre outras finalidades, para exibir anúncios, limitar sua frequência, medir o desempenho e, quando permitido, personalizar a publicidade.</p><p>Para os usuários aplicáveis no EEE, no Reino Unido e na Suíça, o Google Privacidade e mensagens gerencia o consentimento relacionado a cookies de publicidade, armazenamento local e tratamentos associados.</p><p>Consulte as <a href="https://policies.google.com/technologies/ads?hl=pt-BR">informações do Google sobre publicidade</a>.</p></>],
    ["Gerenciamento das preferências de análise", "Os controles de privacidade do próprio lorem-generator.com gerenciam exclusivamente a preferência opcional referente ao Ahrefs Web Analytics. Quando a análise de uso é desativada, a Ahrefs não é carregada nos carregamentos de página seguintes."],
    ["Gerenciamento das preferências de publicidade", "As preferências de publicidade são gerenciadas separadamente pelo sistema de consentimento do Google. Os usuários aplicáveis podem reabrir a interface do Google por meio do controle de configurações de privacidade e cookies e alterar ou revogar as escolhas feitas anteriormente."],
    ["Configurações do navegador", "Você também pode excluir cookies e o armazenamento local pelas configurações do seu navegador. Essa operação pode redefinir as preferências salvas e fazer com que o consentimento seja solicitado novamente."],
    ["Alterações nesta política", "Esta Política de Cookies pode ser atualizada quando houver mudanças nos cookies, nos mecanismos de armazenamento do navegador ou nos serviços de terceiros utilizados pelo lorem-generator.com."]
  ]
} as const;

const dutchPrivacy = {
  title: "Privacyverklaring",
  intro: "Deze privacyverklaring legt uit hoe lorem-generator.com informatie verwerkt wanneer u de website gebruikt.",
  sections: [
    ["Tekstgeneratie", "De Lorem Ipsum-generator en de teksthulpmiddelen op de website werken lokaal in uw browser. Gegenereerde tekst en tekst die u in deze hulpmiddelen invoert, worden niet naar de applicatieserver van de website verzonden."],
    ["Lokale voorkeuren", <><p>De website gebruikt de lokale opslag van uw browser om bepaalde instellingen van de interface te onthouden, zoals uw kleurthema en uw toestemmingsvoorkeur voor webanalyse.</p><p>Deze informatie blijft op uw apparaat staan totdat u uw voorkeuren wijzigt of de opgeslagen browsergegevens verwijdert.</p></>],
    ["Webanalyse", <><p>lorem-generator.com gebruikt Ahrefs Web Analytics om op geaggregeerd niveau inzicht te krijgen in het websiteverkeer en het gebruik van de website.</p><p>Ahrefs beschrijft Web Analytics als een cookievrije dienst en geeft aan daarbij geen persoonsgegevens te verzamelen. Op deze website wordt het Ahrefs-analysescript alleen geladen nadat u toestemming hebt gegeven voor webanalyse.</p><p>U kunt deze voorkeur wijzigen via de privacy-instellingen van de website.</p><p>Meer informatie over <a href="https://ahrefs.com/web-analytics">Ahrefs Web Analytics</a>.</p></>],
    ["Advertenties en Google AdSense", <><p>lorem-generator.com gebruikt Google AdSense om advertenties weer te geven.</p><p>Google en zijn advertentiepartners kunnen cookies, lokale opslag, IP-adressen, webbakens of andere identificatiemiddelen gebruiken voor het weergeven en meten van advertenties, het voorkomen van fraude en, wanneer dit is toegestaan, het personaliseren van advertenties.</p><p>Voor gebruikers in de Europese Economische Ruimte (EER), het Verenigd Koninkrijk en Zwitserland worden advertentiegerelateerde toestemmingsvoorkeuren beheerd via Google Privacy en berichten, een platform voor toestemmingsbeheer dat het Transparency &amp; Consent Framework van IAB Europe ondersteunt.</p><p>Het bericht biedt gebruikers de mogelijkheid toestemming te geven, geen toestemming te geven of afzonderlijke opties voor advertentiedoeleinden en deelnemende leveranciers te beheren.</p><p>Gebruikers kunnen hun advertentievoorkeuren later opnieuw bekijken, wijzigen of hun toestemming intrekken via de privacy- en cookie-instellingen van het toestemmingssysteem van Google.</p><p>Bekijk de <a href="https://policies.google.com/technologies/ads?hl=nl">informatie van Google over advertenties</a>.</p></>],
    ["Hosting en beveiliging", <><p>lorem-generator.com wordt geleverd via de infrastructuur van Cloudflare.</p><p>Wanneer u de website bezoekt, kan Cloudflare beperkte technische informatie verwerken, waaronder IP-adressen, gegevens over de routering van netwerkverkeer, informatie over systeemconfiguratie en andere gegevens over verzoeken die nodig zijn om zijn diensten te leveren, beveiligen en beheren.</p><p>Bekijk de <a href="https://www.cloudflare.com/privacypolicy/">privacydocumentatie van Cloudflare</a>.</p></>],
    ["Bewaartermijnen", <><p>De website maakt geen gebruikersaccounts aan en slaat tekst die met de Lorem Ipsum-hulpmiddelen wordt gegenereerd niet op de applicatieserver op.</p><p>Lokale voorkeuren blijven in uw browser opgeslagen totdat u deze wijzigt of de browsergegevens verwijdert.</p><p>Informatie die door externe dienstverleners wordt verwerkt, wordt bewaard volgens hun eigen privacybeleid en dienstconfiguraties.</p></>],
    ["Uw keuzes en rechten", <><p>Voor zover de toepasselijke privacywetgeving daarin voorziet, kunt u rechten hebben met betrekking tot inzage, rectificatie, verwijdering, beperking van de verwerking, bezwaar, gegevensoverdraagbaarheid en het intrekken van toestemming.</p><p>Het intrekken van toestemming heeft geen invloed op de rechtmatigheid van verwerkingen die vóór de intrekking op basis van die toestemming hebben plaatsgevonden.</p><p>Voor privacygerelateerde verzoeken over lorem-generator.com kunt u contact opnemen via <a href="mailto:privacy@lorem-generator.com">privacy@lorem-generator.com</a>.</p></>],
    ["Diensten van derden", <><p>Meer informatie over de manier waarop externe dienstverleners informatie verwerken, vindt u in hun respectieve privacyverklaringen:</p><ul><li><a href="https://policies.google.com/privacy?hl=nl">Google</a></li><li><a href="https://ahrefs.com/privacy">Ahrefs</a></li><li><a href="https://www.cloudflare.com/privacypolicy/">Cloudflare</a></li></ul></>],
    ["Wijzigingen in deze privacyverklaring", <><p>Deze privacyverklaring kan worden bijgewerkt wanneer de diensten, technologieën of gegevensverwerkingspraktijken van de website veranderen.</p><p>De versie die op deze pagina is gepubliceerd, beschrijft de huidige werking van lorem-generator.com.</p></>]
  ]
} as const;

const dutchCookies = {
  title: "Cookiebeleid",
  intro: "Dit cookiebeleid legt uit hoe lorem-generator.com cookies en browseropslag gebruikt en hoe u uw voorkeuren kunt beheren.",
  sections: [
    ["Noodzakelijke lokale opslag", <><p>De website gebruikt de lokale opslag van uw browser voor bepaalde functies van de interface, waaronder:</p><ul><li>uw voorkeur voor het kleurthema;</li><li>uw opgeslagen toestemmingsvoorkeur voor webanalyse.</li></ul><p>Lokale opslag is geen cookie. Deze waarden blijven op uw apparaat staan totdat u uw voorkeuren wijzigt of de opgeslagen browsergegevens verwijdert.</p></>],
    ["Webanalyse", <><p>Ahrefs Web Analytics wordt alleen gebruikt nadat u toestemming hebt gegeven voor webanalyse.</p><p>Ahrefs beschrijft deze dienst als cookievrij en geeft aan daarbij geen persoonsgegevens te verzamelen.</p><p>Als u geen toestemming geeft voor webanalyse, wordt het Ahrefs-analysescript niet geladen.</p><p>Meer informatie over <a href="https://ahrefs.com/web-analytics">Ahrefs Web Analytics</a>.</p></>],
    ["Cookies en opslag voor advertenties", <><p>Google AdSense kan cookies of andere vormen van lokale opslag gebruiken bij het leveren van advertentiediensten.</p><p>Volgens Google kunnen AdSense-cookies onder meer worden gebruikt voor het weergeven van advertenties, frequentiebeperking, rapportage en, wanneer toegestaan, advertentiepersonalisatie.</p><p>Voor gebruikers in de EER, het Verenigd Koninkrijk en Zwitserland beheert Google Privacy en berichten de toestemming voor advertentiecookies, lokale opslag en de daarmee samenhangende verwerking.</p><p>Bekijk de <a href="https://policies.google.com/technologies/ads?hl=nl">informatie van Google over advertenties</a>.</p></>],
    ["Beheer van voorkeuren voor webanalyse", "De eigen privacy-instellingen van lorem-generator.com beheren uitsluitend de optionele voorkeur voor Ahrefs Web Analytics. Wanneer webanalyse wordt uitgeschakeld, wordt Ahrefs bij volgende paginaladingen niet geladen."],
    ["Beheer van advertentievoorkeuren", "Advertentievoorkeuren worden afzonderlijk beheerd via het toestemmingssysteem van Google. Gebruikers voor wie dit van toepassing is, kunnen de Google-interface opnieuw openen via de privacy- en cookie-instellingen en eerder gemaakte keuzes wijzigen of hun toestemming intrekken."],
    ["Browserinstellingen", "U kunt cookies en lokale opslag ook verwijderen via de instellingen van uw browser. Hierdoor kunnen opgeslagen voorkeuren worden gewist en kan opnieuw om toestemming worden gevraagd."],
    ["Wijzigingen in dit cookiebeleid", "Dit cookiebeleid kan worden bijgewerkt wanneer de cookies, browseropslagmechanismen of externe diensten die lorem-generator.com gebruikt veranderen."]
  ]
} as const;

const turkishPrivacy = {
  title: "Gizlilik Politikası",
  intro: "Bu Gizlilik Politikası, lorem-generator.com sitesini kullandığınızda bilgilerin nasıl işlendiğini açıklar.",
  sections: [
    ["Metin oluşturma", <><p>Lorem Ipsum oluşturma işlemi ve sitedeki metin araçları tarayıcınızda yerel olarak çalışır.</p><p>Oluşturulan metinler ve bu araçlara girdiğiniz metinler sitenin uygulama sunucusuna gönderilmez.</p></>],
    ["Yerel tercihler", <><p>Site, renk teması ve web analiziyle ilgili izin tercihiniz gibi bazı arayüz ayarlarını hatırlamak için tarayıcının yerel depolama özelliğini kullanır.</p><p>Bu bilgiler, tercihlerinizi değiştirene veya tarayıcınızda saklanan verileri silene kadar cihazınızda kalır.</p></>],
    ["Web analizi", <><p>lorem-generator.com, site trafiğini ve kullanımını toplu düzeyde anlamak için Ahrefs Web Analytics kullanır.</p><p>Ahrefs, Web Analytics hizmetini çerez kullanmayan bir hizmet olarak tanımlar ve bu hizmet kapsamında kişisel veri toplamadığını belirtir.</p><p>Bu sitede Ahrefs analiz komut dosyası yalnızca web analizine izin verdikten sonra yüklenir.</p><p>Web analizi tercihinizi sitenin gizlilik kontrolleri üzerinden değiştirebilirsiniz.</p><p><a href="https://ahrefs.com/web-analytics">Ahrefs Web Analytics</a> hakkında daha fazla bilgi.</p></>],
    ["Reklamlar ve Google AdSense", <><p>lorem-generator.com reklam göstermek için Google AdSense kullanır.</p><p>Google ve reklam iş ortakları; reklamların sunulması ve ölçülmesi, dolandırıcılığın önlenmesi ve izin verildiği durumlarda reklamların kişiselleştirilmesi amacıyla çerezler, yerel depolama, IP adresleri, web işaretçileri veya diğer tanımlayıcıları kullanabilir.</p><p>Avrupa Ekonomik Alanı (AEA), Birleşik Krallık ve İsviçre’deki kullanıcılar için reklamlarla ilgili izin tercihleri, IAB Europe Şeffaflık ve Kullanıcı Rızası Çerçevesi’ni destekleyen bir izin yönetimi platformu olan Google Gizlilik ve Mesajlaşma üzerinden yönetilir.</p><p>Gösterilen mesaj, kullanıcıların izin vermesine, izin vermemesine veya reklam amaçları ve ilgili sağlayıcılar için seçenekleri ayrı ayrı yönetmesine olanak tanır.</p><p>Kullanıcılar daha sonra Google’ın izin sistemi tarafından sunulan gizlilik ve çerez ayarları üzerinden reklam tercihlerini yeniden inceleyebilir, değiştirebilir veya daha önce verdikleri izni geri alabilir.</p><p><a href="https://policies.google.com/technologies/ads?hl=tr">Google’ın reklamlarla ilgili bilgileri</a>.</p></>],
    ["Barındırma ve güvenlik", <><p>lorem-generator.com, Cloudflare altyapısı üzerinden sunulur.</p><p>Siteye erişildiğinde Cloudflare; hizmetlerini sunmak, güvenliğini sağlamak ve işletmek için gerekli olan IP adresleri, trafik yönlendirme verileri, sistem yapılandırma bilgileri ve isteklere ilişkin diğer sınırlı teknik bilgileri işleyebilir.</p><p><a href="https://www.cloudflare.com/privacypolicy/">Cloudflare gizlilik belgeleri</a> hakkında daha fazla bilgi.</p></>],
    ["Verilerin saklanması", <><p>Site kullanıcı hesabı oluşturmaz ve Lorem Ipsum araçlarıyla oluşturulan metinleri uygulama sunucusunda saklamaz.</p><p>Yerel tercihler, siz değiştirene veya tarayıcı verilerini silene kadar tarayıcınızda saklanır.</p><p>Üçüncü taraf hizmet sağlayıcılar tarafından işlenen bilgiler, ilgili sağlayıcıların kendi gizlilik politikaları ve hizmet yapılandırmaları doğrultusunda saklanır.</p></>],
    ["Tercihleriniz ve haklarınız", <><p>Uygulanabilir veri koruma mevzuatının öngördüğü ölçüde; erişim, düzeltme, silme, işlemenin kısıtlanması, itiraz, veri taşınabilirliği ve rızanın geri alınmasıyla ilgili haklara sahip olabilirsiniz.</p><p>Rızanın geri alınması, geri alma işleminden önce rızaya dayanılarak gerçekleştirilen işlemlerin hukuka uygunluğunu etkilemez.</p><p>lorem-generator.com ile ilgili gizlilik talepleri için <a href="mailto:privacy@lorem-generator.com">privacy@lorem-generator.com</a> adresinden iletişime geçebilirsiniz.</p></>],
    ["Üçüncü taraf hizmetleri", <><p>Üçüncü taraf hizmet sağlayıcıların bilgileri nasıl işlediği hakkında daha fazla bilgi için ilgili gizlilik politikalarını inceleyebilirsiniz:</p><ul><li><a href="https://policies.google.com/privacy?hl=tr">Google</a></li><li><a href="https://ahrefs.com/privacy">Ahrefs</a></li><li><a href="https://www.cloudflare.com/privacypolicy/">Cloudflare</a></li></ul></>],
    ["Bu politikadaki değişiklikler", "Bu Gizlilik Politikası, sitenin kullandığı hizmetler, teknolojiler veya veri işleme uygulamaları değiştiğinde güncellenebilir. Bu sayfada yayımlanan sürüm lorem-generator.com’un mevcut işleyişini açıklar."]
  ]
} as const;

const turkishCookies = {
  title: "Çerez Politikası",
  intro: "Bu politika, lorem-generator.com’un çerezleri ve tarayıcı depolamasını nasıl kullandığını ve tercihlerinizi nasıl yönetebileceğinizi açıklar.",
  sections: [
    ["Gerekli yerel depolama", <><p>Site, aşağıdakiler dahil olmak üzere bazı arayüz işlevleri için tarayıcının yerel depolama özelliğini kullanır:</p><ul><li>renk teması tercihiniz;</li><li>web analiziyle ilgili kaydedilmiş izin tercihiniz.</li></ul><p>Yerel depolama bir çerez değildir. Bu değerler, tercihlerinizi değiştirene veya tarayıcınızda saklanan verileri silene kadar cihazınızda kalır.</p></>],
    ["Web analizi", <><p>Ahrefs Web Analytics yalnızca kullanıcı web analizine izin verdikten sonra kullanılır.</p><p>Ahrefs bu hizmeti çerez kullanmayan bir hizmet olarak tanımlar ve bu hizmet kapsamında kişisel veri toplamadığını belirtir.</p><p>Web analizine izin verilmezse Ahrefs analiz komut dosyası yüklenmez.</p><p><a href="https://ahrefs.com/web-analytics">Ahrefs Web Analytics</a> hakkında daha fazla bilgi.</p></>],
    ["Reklamlar için çerezler ve yerel depolama", <><p>Google AdSense, reklam hizmetlerini sunarken çerezleri veya diğer yerel depolama yöntemlerini kullanabilir.</p><p>Google’a göre AdSense çerezleri; reklamların gösterilmesi, gösterim sıklığının sınırlandırılması, performansın ölçülmesi ve izin verildiği durumlarda reklamların kişiselleştirilmesi gibi amaçlarla kullanılabilir.</p><p>AEA, Birleşik Krallık ve İsviçre’deki ilgili kullanıcılar için Google Gizlilik ve Mesajlaşma; reklam çerezleri, yerel depolama ve bunlarla ilişkili veri işleme faaliyetlerine ilişkin izinleri yönetir.</p><p><a href="https://policies.google.com/technologies/ads?hl=tr">Google’ın reklamlarla ilgili bilgileri</a>.</p></>],
    ["Web analizi tercihlerinin yönetimi", "lorem-generator.com’un kendi gizlilik kontrolleri yalnızca Ahrefs Web Analytics için isteğe bağlı izin tercihini yönetir. Web analizi devre dışı bırakıldığında Ahrefs sonraki sayfa yüklemelerinde yüklenmez."],
    ["Reklam tercihlerinin yönetimi", "Reklam tercihleri Google’ın izin sistemi üzerinden ayrı olarak yönetilir. İlgili kullanıcılar Google arayüzünü gizlilik ve çerez ayarları üzerinden yeniden açabilir ve daha önce yaptıkları seçimleri değiştirebilir veya verdikleri izni geri alabilir."],
    ["Tarayıcı ayarları", "Çerezleri ve yerel depolamayı tarayıcı ayarlarınız üzerinden de silebilirsiniz. Bu işlem kayıtlı tercihleri sıfırlayabilir ve yeniden izin istenmesine neden olabilir."],
    ["Bu politikadaki değişiklikler", "Bu Çerez Politikası, lorem-generator.com tarafından kullanılan çerezler, tarayıcı depolama yöntemleri veya üçüncü taraf hizmetleri değiştiğinde güncellenebilir."]
  ]
} as const;

const polishPrivacy = {
  title: "Polityka prywatności",
  intro: "Niniejsza Polityka prywatności wyjaśnia, jak lorem-generator.com przetwarza informacje podczas korzystania z witryny.",
  sections: [
    ["Generowanie tekstu", <p key="generowanie">Generowanie Lorem Ipsum i narzędzia tekstowe działają lokalnie w przeglądarce. Wygenerowany tekst oraz tekst wpisany do narzędzi nie są wysyłane na serwer aplikacji.</p>],
    ["Preferencje lokalne", <p key="preferencje">Witryna korzysta z pamięci lokalnej przeglądarki, aby zapamiętać ustawienia interfejsu, takie jak motyw kolorystyczny i zgoda na analitykę. Informacje pozostają na urządzeniu do czasu zmiany preferencji lub wyczyszczenia pamięci przeglądarki.</p>],
    ["Analityka", <Fragment key="analityka"><p>lorem-generator.com używa Ahrefs Web Analytics do analizy zagregowanego ruchu i korzystania z witryny. Ahrefs opisuje tę usługę jako bezplikową i deklaruje, że nie zbiera danych osobowych. Skrypt Ahrefs jest ładowany dopiero po wyrażeniu zgody na analitykę.</p><p>Preferencję można zmienić w ustawieniach prywatności witryny.</p><p>Więcej informacji: <a href="https://ahrefs.com/web-analytics">Ahrefs Web Analytics</a>.</p></Fragment>],
    ["Reklamy i Google AdSense", <Fragment key="reklamy"><p>lorem-generator.com używa Google AdSense do wyświetlania reklam.</p><p>Google i jego partnerzy reklamowi mogą używać plików cookie, pamięci lokalnej, adresów IP, sygnałów web beacon lub innych identyfikatorów do dostarczania i pomiaru reklam, zapobiegania oszustwom oraz, gdy jest to dozwolone, personalizacji reklam.</p><p>Dla użytkowników z EOG, Wielkiej Brytanii i Szwajcarii zgody reklamowe są zarządzane przez Google Privacy &amp; Messaging, platformę zgodną z IAB Europe Transparency &amp; Consent Framework.</p><p>Informacje Google o reklamach: <a href="https://policies.google.com/technologies/ads?hl=pl">policies.google.com</a>.</p></Fragment>],
    ["Hosting i bezpieczeństwo", <Fragment key="hosting"><p>lorem-generator.com działa w infrastrukturze Cloudflare. Cloudflare może przetwarzać ograniczone informacje techniczne, takie jak adres IP, dane routingu i konfiguracji systemu, niezbędne do dostarczania i zabezpieczania usług.</p><p><a href="https://www.cloudflare.com/privacypolicy/">Dokumentacja prywatności Cloudflare</a>.</p></Fragment>],
    ["Przechowywanie danych", <p key="przechowywanie">Witryna nie tworzy kont użytkowników i nie przechowuje wygenerowanego tekstu na serwerze aplikacji. Preferencje lokalne pozostają w przeglądarce do czasu ich zmiany lub wyczyszczenia pamięci. Dane przetwarzane przez dostawców zewnętrznych są przechowywane zgodnie z ich politykami.</p>],
    ["Wybory i prawa użytkownika", <Fragment key="prawa"><p>W zakresie wymaganym przez prawo możesz mieć prawa dostępu, sprostowania, usunięcia, ograniczenia przetwarzania, sprzeciwu, przenoszenia danych i wycofania zgody.</p><p>Wycofanie zgody nie wpływa na zgodność z prawem wcześniejszego przetwarzania.</p><p>W sprawach prywatności skontaktuj się: <a href="mailto:privacy@lorem-generator.com">privacy@lorem-generator.com</a>.</p></Fragment>],
    ["Usługi zewnętrzne", <Fragment key="uslugi"><p>Informacje o przetwarzaniu przez dostawców zewnętrznych:</p><ul><li><a href="https://policies.google.com/privacy?hl=pl">Google</a></li><li><a href="https://ahrefs.com/privacy">Ahrefs</a></li><li><a href="https://www.cloudflare.com/privacypolicy/">Cloudflare</a></li></ul></Fragment>],
    ["Zmiany w polityce", <p key="zmiany">Polityka może być aktualizowana, gdy zmienią się usługi, technologie lub praktyki przetwarzania danych witryny. Wersja opublikowana na tej stronie opisuje bieżące działanie lorem-generator.com.</p>]
  ]
} as const;

const polishCookies = {
  title: "Polityka cookies",
  intro: "Niniejsza polityka wyjaśnia, jak lorem-generator.com używa plików cookie i pamięci przeglądarki oraz jak zarządzać preferencjami.",
  sections: [
    ["Niezbędna pamięć przeglądarki", <Fragment key="niezbędna"><p>Witryna używa pamięci lokalnej przeglądarki do podstawowych funkcji interfejsu, w tym:</p><ul><li>preferencji motywu kolorystycznego;</li><li>zapisanej zgody na analitykę.</li></ul><p>Pamięć lokalna nie jest plikiem cookie i pozostaje na urządzeniu do czasu zmiany ustawień lub wyczyszczenia pamięci.</p></Fragment>],
    ["Analityka", <Fragment key="analityka"><p>Ahrefs Web Analytics jest używany wyłącznie po wyrażeniu zgody na analitykę.</p><p>Ahrefs opisuje usługę jako bezplikową i deklaruje brak zbierania danych osobowych. Bez zgody skrypt Ahrefs nie jest ładowany.</p><p><a href="https://ahrefs.com/web-analytics">Więcej o Ahrefs Web Analytics</a>.</p></Fragment>],
    ["Reklamy i pamięć lokalna", <Fragment key="reklamy-lokalna"><p>Google AdSense może używać plików cookie lub pamięci lokalnej podczas świadczenia usług reklamowych.</p><p>Dla użytkowników z EOG, Wielkiej Brytanii i Szwajcarii Google Privacy &amp; Messaging zarządza zgodą na reklamy i powiązane przetwarzanie.</p><p><a href="https://policies.google.com/technologies/ads?hl=pl">Informacje Google o reklamach</a>.</p></Fragment>],
    ["Zarządzanie preferencjami analityki", <p key="zarzadzanie-analityka">Ustawienia prywatności witryny zarządzają opcjonalną analityką Ahrefs. Po jej wyłączeniu Ahrefs nie jest ładowany przy kolejnych wizytach.</p>],
    ["Zarządzanie preferencjami reklam", <p key="zarzadzanie-reklam">Preferencje reklam są zarządzane osobno przez system zgody Google. Możesz ponownie otworzyć ustawienia prywatności i cookies oraz zmienić wcześniejsze wybory.</p>],
    ["Ustawienia przeglądarki", <p key="ustawienia">Pliki cookie i pamięć lokalną można usunąć w ustawieniach przeglądarki. Może to zresetować preferencje i spowodować ponowne pytanie o zgodę.</p>],
    ["Zmiany w polityce", <p key="zmiany">Polityka może być aktualizowana, gdy zmienią się pliki cookie, mechanizmy pamięci przeglądarki lub usługi zewnętrzne używane przez lorem-generator.com.</p>]
  ]
} as const;

const hungarianPrivacy = {
  title: "Adatvédelmi szabályzat",
  intro: "Ez az adatvédelmi szabályzat bemutatja, hogyan kezeli a lorem-generator.com az információkat a webhely használata során.",
  sections: [
    ["Szöveggenerálás", <p key="szoveg">A Lorem Ipsum generálása és az oldalon elérhető szöveges eszközök helyben, a böngészőben működnek. A generált és a beírt szöveget az oldal nem küldi az alkalmazás szerverére.</p>],
    ["Helyi beállítások", <p key="helyi">Az oldal a böngésző helyi tárhelyét használja a kezelőfelület beállításainak, például a színtémának és az analitikai hozzájárulással kapcsolatos választásnak a megjegyzésére. Ezek az információk mindaddig az eszközödön maradnak, amíg nem módosítod a beállításaidat, vagy nem törlöd a böngészőben tárolt adatokat.</p>],
    ["Analitika", <Fragment key="analitika-hu"><p>A lorem-generator.com az összesített webhelyforgalom és használat megértéséhez Ahrefs Web Analyticset használ. Az Ahrefs cookie-mentes szolgáltatásként írja le a Web Analytics szolgáltatását, és azt állítja, hogy nem gyűjt személyes adatokat. Ezen az oldalon az Ahrefs analitikai szkriptje csak azután töltődik be, hogy engedélyezted az analitikát.</p><p>Az analitikai beállításodat az oldal adatvédelmi vezérlőivel módosíthatod.</p><p>További információ: <a href="https://ahrefs.com/web-analytics">Ahrefs Web Analytics</a>.</p></Fragment>],
    ["Hirdetések és Google AdSense", <Fragment key="hirdetes-hu"><p>A lorem-generator.com Google AdSense-t használ hirdetések megjelenítésére.</p><p>A Google és hirdetési partnerei cookie-kat, helyi tárhelyet, IP-címeket, webjelzőket vagy más azonosítókat használhatnak a hirdetések megjelenítésével, mérésével, a csalások megelőzésével és – ahol ez megengedett – a hirdetések személyre szabásával kapcsolatban.</p><p>Az Európai Gazdasági Térségben, az Egyesült Királyságban és Svájcban élő felhasználók esetében a hirdetési hozzájárulást a Google Privacy &amp; Messaging kezeli. Ez egy olyan hozzájárulás-kezelő platform, amely támogatja az IAB Europe Transparency &amp; Consent Framework keretrendszerét. Az üzenet lehetővé teszi, hogy a felhasználók hozzájáruljanak, elutasítsák a hozzájárulást, vagy egyenként kezeljék a hirdetési célokra és a részt vevő szolgáltatókra vonatkozó beállításokat.</p><p>A felhasználók később a Google hozzájárulási rendszere által biztosított Adatvédelmi és cookie-beállítások segítségével áttekinthetik vagy visszavonhatják hirdetési hozzájárulásukat.</p><p>Lásd a <a href="https://policies.google.com/technologies/ads?hl=hu">Google hirdetésekkel kapcsolatos tájékoztatóját</a>.</p></Fragment>],
    ["Tárhely és biztonság", <Fragment key="tarhely-hu"><p>A lorem-generator.com a Cloudflare infrastruktúráján keresztül érhető el. Amikor a felhasználók a Cloudflare-en keresztül kiszolgált webhelyeket keresnek fel, a Cloudflare korlátozott technikai információkat dolgozhat fel, például IP-címeket, forgalomirányítási adatokat, rendszerkonfigurációs információkat és a kérésekhez kapcsolódó egyéb adatokat, amelyek szolgáltatásai nyújtásához, biztonságossá tételéhez és működtetéséhez szükségesek.</p><p>Lásd a <a href="https://www.cloudflare.com/privacypolicy/">Cloudflare adatvédelmi dokumentációját</a>.</p></Fragment>],
    ["Adatmegőrzés", <p key="adatmegorzes">Az oldal nem hoz létre felhasználói fiókokat, és nem tárolja az alkalmazás szerverén a Lorem Ipsum eszközökkel generált szöveget. A helyi beállítások mindaddig a böngésződben maradnak, amíg nem módosítod őket, vagy nem törlöd a böngészőben tárolt adatokat. A külső szolgáltatók által feldolgozott információkat az adott szolgáltatók saját szabályzataiknak és szolgáltatásbeállításaiknak megfelelően őrzik meg.</p>],
    ["Választási lehetőségek és jogok", <Fragment key="jogok-hu"><p>Az alkalmazandó adatvédelmi jogszabályok alapján hozzáférési, helyesbítési, törlési, korlátozási, tiltakozási, adathordozhatósági és hozzájárulás-visszavonási jogaid lehetnek.</p><p>A hozzájárulás visszavonása nem érinti a visszavonás előtt végzett adatkezelés jogszerűségét.</p><p>Adatvédelmi kérdésekben írj a <a href="mailto:privacy@lorem-generator.com">privacy@lorem-generator.com</a> címre.</p></Fragment>],
    ["Külső szolgáltatások", <Fragment key="kulso-hu"><p>A külső szolgáltatók adatkezeléséről az alábbi tájékoztatókban olvashatsz:</p><ul><li><a href="https://policies.google.com/privacy?hl=hu">Google</a></li><li><a href="https://ahrefs.com/privacy">Ahrefs</a></li><li><a href="https://www.cloudflare.com/privacypolicy/">Cloudflare</a></li></ul></Fragment>],
    ["A szabályzat módosításai", <p key="modositas-hu">Ez az adatvédelmi szabályzat frissülhet, ha változnak az oldal szolgáltatásai, technológiái vagy adatkezelési gyakorlatai. Az ezen az oldalon közzétett változat a lorem-generator.com jelenlegi működését tükrözi.</p>]
  ]
} as const;

const hungarianCookies = {
  title: "Cookie-szabályzat",
  intro: "Ez a szabályzat bemutatja, hogyan használja a lorem-generator.com a cookie-kat és a böngésző tárhelyét, valamint hogyan kezelheted a választásaidat.",
  sections: [
    ["Szükséges böngészőtárhely", <Fragment key="tarhely-szukseges-hu"><p>Az oldal a helyi tárhelyet alapvető felületi funkciókhoz használja, többek között:</p><ul><li>a színtéma beállításához;</li><li>az analitikai hozzájárulás mentéséhez.</li></ul><p>A helyi tárhely nem cookie. Ezek az értékek mindaddig az eszközödön maradnak, amíg nem módosítod a beállításaidat, vagy nem törlöd a böngészőben tárolt adatokat.</p></Fragment>],
    ["Analitika", <Fragment key="analitika-hu"><p>Az Ahrefs Web Analytics csak az analitikai hozzájárulás megadása után használható.</p><p>Az Ahrefs ezt a szolgáltatást cookie-mentesként írja le, és azt állítja, hogy nem gyűjt személyes adatokat. Ha nem adsz hozzájárulást az analitikához, az Ahrefs analitikai szkriptje nem töltődik be.</p><p><a href="https://ahrefs.com/web-analytics">További információ az Ahrefs Web Analyticsről</a>.</p></Fragment>],
    ["Hirdetési cookie-k és tárhely", <Fragment key="cookie-hu"><p>A Google AdSense cookie-kat vagy a helyi tárolás más formáit használhatja a hirdetési szolgáltatások nyújtása során. A Google tájékoztatása szerint az AdSense cookie-kat többek között a hirdetések megjelenítésére, a gyakoriság szabályozására, jelentéskészítésre és – ahol ez megengedett – személyre szabásra használja.</p><p>Az Európai Gazdasági Térségben, az Egyesült Királyságban és Svájcban élő jogosult felhasználók esetében a Google Privacy &amp; Messaging kezeli a hirdetési cookie-khoz, a helyi tárhelyhez és a kapcsolódó adatkezeléshez való hozzájárulást.</p><p>Lásd a <a href="https://policies.google.com/technologies/ads?hl=hu">Google hirdetésekkel kapcsolatos tájékoztatóját</a>.</p></Fragment>],
    ["Analitikai beállítások kezelése", <p key="analitika-beallitas-hu">Az oldal adatvédelmi beállításai kezelik az Ahrefs opcionális analitikáját. Kikapcsolás után az Ahrefs nem töltődik be a következő oldalbetöltéseknél.</p>],
    ["Hirdetési beállítások kezelése", <p key="hirdetesi-beallitas-hu">A hirdetési beállításokat külön a Google hozzájárulási rendszere kezeli. A jogosult felhasználók az Adatvédelmi és cookie-beállítások vezérlővel újra megnyithatják a Google hozzájárulási felületét, és módosíthatják vagy visszavonhatják korábbi választásaikat.</p>],
    ["Böngészőbeállítások", <p key="bongeszo-hu">A cookie-kat és a helyi tárhelyet a böngésző beállításaiban is törölheted. Ez visszaállíthatja a mentett beállításokat, és azt eredményezheti, hogy a rendszer ismét hozzájárulást kér.</p>],
    ["A szabályzat módosításai", <p key="modositas-hu">A szabályzat frissülhet, ha változnak a cookie-k, a böngészőtárhely mechanizmusai vagy a lorem-generator.com külső szolgáltatásai.</p>]
  ]
} as const;

export function LegalPage({ language, kind }: { language: LegalLanguage; kind: LegalKind }) {
  const copy = language === "es" ? (kind === "cookies" ? spanishCookies : spanishPrivacy) : language === "fr" ? (kind === "cookies" ? frenchCookies : frenchPrivacy) : language === "de" ? (kind === "cookies" ? germanCookies : germanPrivacy) : language === "pt-BR" ? (kind === "cookies" ? brazilianPortugueseCookies : brazilianPortuguesePrivacy) : language === "nl-NL" ? (kind === "cookies" ? dutchCookies : dutchPrivacy) : language === "tr" ? (kind === "cookies" ? turkishCookies : turkishPrivacy) : language === "pl" ? (kind === "cookies" ? polishCookies : polishPrivacy) : language === "hu" ? (kind === "cookies" ? hungarianCookies : hungarianPrivacy) : content[language][kind];
  const isItalian = language === "it";
  const isSpanish = language === "es";
  const isFrench = language === "fr";
  const isGerman = language === "de";
  const isBrazilianPortuguese = language === "pt-BR";
  const isDutch = language === "nl-NL";
  const isTurkish = language === "tr";
  const isPolish = language === "pl";
  const isHungarian = language === "hu";
  const home = isItalian ? "/it/" : isSpanish ? "/es/" : isFrench ? "/fr/" : isGerman ? "/de/" : isBrazilianPortuguese ? "/pt-br/" : isDutch ? "/nl/" : isTurkish ? "/tr/" : isPolish ? "/pl/" : isHungarian ? "/hu/" : "/";

  return <main className="site-shell legal-shell" lang={language === "nl-NL" ? "nl" : language}>
    <article className="page-content legal-content">
      <a className="legal-back" href={home}>{isItalian ? "← Torna al generatore" : isSpanish ? "← Volver al generador" : isFrench ? "← Retour au générateur" : isGerman ? "← Zurück zum Generator" : isBrazilianPortuguese ? "← Voltar ao gerador" : isDutch ? "← Terug naar de generator" : isTurkish ? "← Oluşturucuya dön" : isPolish ? "← Wróć do generatora" : isHungarian ? "← Vissza a generátorhoz" : "← Back to generator"}</a>
      <span className="legal-eyebrow">{isItalian ? "LEGALE" : isFrench ? "LÉGAL" : isGerman ? "RECHTLICHES" : isDutch ? "JURIDISCH" : isTurkish ? "YASAL" : isPolish ? "PRAWO" : isHungarian ? "JOGI" : "LEGAL"}</span>
      <h1>{copy.title}</h1>
      <p className="legal-intro">{copy.intro}</p>
      <div className="legal-sections">
        {copy.sections.map(([heading, body]) => (
          <section key={heading}>
            <h2>{heading}</h2>
            {typeof body === "string" ? <p>{body}</p> : body}
          </section>
        ))}
      </div>
    </article>
  </main>;
}
